In [1]:
# New Notebook To Practice Python

In [2]:
name = "Omar" # string
age = 20 #integer
is_student = True #boolean

In [3]:
# The difference Between = and ==

In [4]:
x = 30 # = is an assignment operator, so it assigns a value. It means "x is now 30."

y = 15

# == checks if two things are equal to each other
if x == y:
    print("They are equal!")
else:
    print("They are not equal.")

They are not equal.


In [5]:
# How to print variables in a statement:

In [6]:
name = "Omar"

# You can use + or , to join strings and variables in a print statement
print("Hello " + name +' ' + "How are you?") # With +, you have to add a space
print("Hello", name, 'Whats up!') # With , it adds spaces in between for you
print("Hello Omar")

Hello Omar How are you?
Hello Omar Whats up!
Hello Omar


If Statements

If statements and conditionals let your code make decisions.

If a condition is true, run this part of code.

If it is false, run a different part of code.

In [7]:
# example with numbers:

temperature = 90

if temperature > 80:
    print("It's hot!")
elif temperature >= 60:
    print("It's nice.")
else:
    print("It's cold.")

It's hot!


if condition:
    # code if this condition is true will run
    # second line i want to run. must be indented
elif another_condition:
    # code if first condition is false, and this other condition is true will run
else:
    # code if none of the above are true

if condition:
    if another_condition:
        # code will run if BOTH if statements are true.
else:
    # code will run if first if statement is not true

In [8]:
# If, Else, elif Examples

Temperture = 105

if Temperture >= 100:
    print ('Its extremly hot bring water!!!')
elif Temperture < 60:
    print ('Nice and cool outside')
else:
    print ('Nice! Go Outide!')

Its extremly hot bring water!!!


In [9]:
grade = 70

if grade >= 90:
    print("A")
elif grade >= 80:
    print("B")
elif grade >= 70:
    print("C")
else:
    print("Fail")

C


While Loops

While loops basically tell the computer to run a piece of code as long as a certain condition is true.
Think of it like: "Keep doing this code while this is true"

In [10]:
count = 1

while count <= 20:
    print("Count is:", count)
    count = count + 1 
#updating the variable is very important so we don't run into infinite loops

Count is: 1
Count is: 2
Count is: 3
Count is: 4
Count is: 5
Count is: 6
Count is: 7
Count is: 8
Count is: 9
Count is: 10
Count is: 11
Count is: 12
Count is: 13
Count is: 14
Count is: 15
Count is: 16
Count is: 17
Count is: 18
Count is: 19
Count is: 20


In [1]:
count = 20

while count <= 30:
    print('Count is', count)
    count = count + 1
# New Count    

Count is 20
Count is 21
Count is 22
Count is 23
Count is 24
Count is 25
Count is 26
Count is 27
Count is 28
Count is 29
Count is 30


In [1]:
password = ""

while password != "password":
    password = input ("Enter the password: ")
    print("Incorrect. Try again.")
    
print("Access granted.")

Enter the password:  password


Incorrect. Try again.
Access granted.


For Loops

Similar to a while loop in the sense that it repeats code.
A for loop goes through items in a list or range, and runs code for each item.

One way: Traverse through a list

In [2]:
fruits_list = ["apple", "orange", "banana", "cherry"]

for fruit in fruits_list:
    print("I like", fruit)

I like apple
I like orange
I like banana
I like cherry


In [3]:
# Creating an array

In [12]:
import numpy as np

my_array = np.array([5, 6, 7, 8, 9])
print(my_array)

[5 6 7 8 9]


In [13]:
print(my_array.size) # How many items are in the array

5


In [14]:
my_array_doubled = my_array * 2 # multiples an entire array / list
print(my_array_doubled)

[10 12 14 16 18]


In [15]:
first_item = my_array[0]
print(first_item)

5


In [16]:
print(my_array[2]*3)

21


In [17]:
print(my_array)

[5 6 7 8 9]


In [18]:
print(my_array[:3])

[5 6 7]


In [19]:
print(my_array[1:4])

[6 7 8]


In [20]:
# 2D Arrays

Think of 2D arrays as like a table. There will be rows and columns.

In [25]:
my_2D_array = [5,8,9], [2,6,7], [2,1,4]

In [26]:
print(my_2D_array)

([5, 8, 9], [2, 6, 7], [2, 1, 4])


In [27]:
my_2D_array = np.zeros((3, 4)) # 3 rows, 4 columns
print(my_2D_array)
print()

my_2D_array[0,0] = 4 # change one number
print(my_2D_array)
print()

my_2D_array[0] = 1 # change a whole row
print(my_2D_array)
print()

my_2D_array[:, 0] = 2
print(my_2D_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[4. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[2. 1. 1. 1.]
 [2. 0. 0. 0.]
 [2. 0. 0. 0.]]


To generate a random number, we use the random.randint(a, b) function.  
generates a random number from a to b.

In [29]:
random_number = np.random.randint(0,10)
print(random_number)

5


In [30]:
# To generate a random choice from a list, we used np.random.choice(list)

In [31]:
lunch_options = ["Pork Chops", "Pizza", "Salad", "Burger", "Tacos", "Quasadillas"]
what_i_will_eat = np.random.choice(lunch_options)
print(what_i_will_eat)

Burger
